# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: protonwire

snapshot:
  # This should be semver otherwise triggers https://github.com/goreleaser/goreleaser/issues/2081
  name_template: "{{ .Version }}-{{.ShortCommit}}-dev"

builds:
  - skip: true

changelog:
  sort: asc
  groups:
    - title: "🍒 Features & Enhancements"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "🚧 Maintenance"
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 2
    - title: "🖥️ Metadata API"
      regexp: "^.*metadata[(\\w)]*:+.*$"
      order: 4
  filters:
    exclude:
      - '^.*doc(s)?[(\\w)]*:+.*$'
      - '^.*release(s)?[(\\w)]*:+.*$'
      - '^.*bot(s)?[(\\w)]*:+.*$'

release:
  mode: replace
  prerelease: auto

  # Set this to true if you want to disable just the artifact upload to the SCM.
  # If this is true, GoReleaser will still create the release with the
  # changelog, but won't upload anything to it.
  #
  # Since: v1.11
  # Templates: allowed (since v1.15)
  skip_upload: true
