name: Bug Report
description: Report a bug
title: "[BUG] -  "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        - Thanks for taking the time to fill out this bug report!

  # version
  - type: input
    id: version
    attributes:
      label: Version
      description: |
        - Version of the software you are running
        - If unable to detect or not applicable, leave the field as is.
      value: NA
    validations:
      required: true

  - type: checkboxes
    id: credential-validation
    attributes:
      label: Credential Validation
      options:
        - label: I have verified that the servers I am trying to connect to are available under my plan.
          required: true

  # Arch
  - type: input
    id: arch
    attributes:
      label: System Architecture
      description: |
        - Output of `uname -m` command.
        - If unable to detect or not applicable, leave the field as is.
      value: NA
    validations:
      required: true

  # Kernel version
  - type: input
    id: kernel-version
    attributes:
      label: Kernel Version
      description: |
        - Output of `uname -r` command.
        - If unable to detect or not applicable, leave the field as is.
      value: NA
    validations:
      required: true

  # nas
  - type: dropdown
    id: nas
    attributes:
      label: Running on a NAS?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: Runtime
      multiple: true
      options:
        - Manually via CLI
        - Systemd Unit
        - Systemd Unit as podman container
        - docker
        - Kubernetes/k3s with containerd
        - Kubernetes/k3s with cri-o
        - I don't know!
        - None of the above, I have mentioned the details in additional info section.
    validations:
      required: true

  - type: textarea
    id: runtime-info
    attributes:
      label: Version of Runtime
      description: |
          - For kubernetes paste output of `kubectl version -o json`
          - For systemd paste output of `systemd --version && resolvectl status --no-pager`
          - If using docker, paste the output of command `docker info`
          - If using podman, paste the output of command `podman info`
          - If using systemd with podman, paste the output of command `podman info && systemd --version`
          - If not using any of the above, please specify your runtime info.
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Your configuration
      description: |
          - For docker-compose, include your docker-compose file.
          - For kubernetes, include your Pod/Deployment, Service and Network configurations.
          - For systemd include your systemd unit files.
      value: NA
      render: markdown

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting & Runtime
      description: |
        - Check common troubleshooting steps.
      options:
        - label: I have reviewed [troubleshooting steps](https://protonwire.prasadt.com/troubleshooting)
          required: true
        - label: I am **NOT** using container runtime which use user-mode networking, [Docker Rootless](https://docs.docker.com/engine/security/rootless/), [gVisor](https://gvisor.dev), [Podman Rootless](https://github.com/containers/podman/blob/main/rootless.md) etc.
          required: true
        - label: I am using latest stable version
          required: true

  # Logs
  - type: textarea
    id: logs
    attributes:
      label: Container/Pod/systemd Log output
      description: |
        - What do you see when you run the script with debug logs enabled
          - Set env variable `DEBUG` to 1
          - Use `--debug` cli flag
          - Add drop-in unit to enable DEBUG or run with `systemd-run --env DEBUG=1`
      render: log

  - type: textarea
    id: additional-info
    attributes:
      label: Any additional info
      description: Any additional details like steps to reproduce intermittent bugs, race conditions etc.

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct & PII Redaction
      description: |
        By submitting this issue, you agree to follow code of conduct for this repository.
        In case the repository is missing code of conduct, Contributor Covenant code of conduct applies.
        Please also ensure that you remove or redact any sensitive personally identifying information
        like IP addresses and secrets like your API keys from logs and report included here.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I have removed any sensitive personally identifying information(PII) and secrets from in this issue report.
          required: true
