#!/usr/bin/bash
# shellcheck shell=bash

set -e
export LOG_FMT="full"
if [[ $DEBUG == "1" ]]; then
  export LOG_LVL=0
fi

if [[ -f /usr/share/shlib/logger.sh ]]; then
  # shellcheck disable=SC1091
  source /usr/share/shlib/logger.sh
else
  echo "[ERROR ] Failed to load logging library expected at /usr/share/shlib/logger.sh"
  exit 1
fi

if [[ $DEBUG == "1" ]]; then
  LOG_LVL="0"
fi

log_info "Refreshing Metadata for Servers"

if PVPN_DEBUG="${DEBUG:-0}" protonvpn refresh; then
  log_success "Refreshed metadata"
else
  log_error "Failed to refresh metadata!"
  exit 1
fi
