#!/bin/bash
log() {
    local msg="$*"
    printf "%s \n" "$msg"
}

info() {
    local msg="$*"
    printf "==> %s \n" "$msg"
}

function main() {
    declare -a docker_extra_args=()
    declare -a cli_args=()
    declare give_shell="false"

    while [[ ${1} != "" ]]; do
        case ${1} in
        --shell | -s)
            give_shell="true"
            ;;
        *)
            cli_args+=("$1")
            ;;
        esac
        shift
    done

    # For local testing - socat UNIX-RECV:./notify.sock,mode=777 -
    if [[ -S ./notify.sock ]]; then
        extra_args+=(
            "-e" "NOTIFY_SOCKET=/tmp/notify.sock"
            "-e" "WATCHDOG_USEC=${WATCHDOG_USEC:-20000000}"
            "--mount" "type=bind,src=$(pwd)/notify.sock,dst=/tmp/notify.sock"
        )
    fi

    if [[ $give_shell == "true" ]]; then
        info "Dropping you in shell"
        docker run \
            -it \
            --rm \
            --name=protonwire_dev \
            --init \
            -e DEBUG \
            -e PROTONVPN_SERVER \
            -e IPCHECK_INTERVAL=${IPCHECK_INTERVAL:-10} \
            -e KILL_SWITCH=${KILL_SWITCH:-1} \
            -e SKIP_DNS_CONFIG \
            -e IPCHECK_URL \
            --cap-add=CAP_NET_ADMIN \
            --userns=host \
            -p=8000:80 \
            -v $(pwd)/protonwire:/usr/bin/protonwire:ro \
            --mount type=bind,src="$(pwd)"/private.key,dst=/etc/protonwire/private-key,readonly \
            --sysctl net.ipv4.conf.all.rp_filter=2 \
            --tmpfs /tmp \
            --entrypoint /bin/bash \
            "${extra_args[@]}" \
            ghcr.io/tprasadtp/protonwire:dev
    else
        docker run \
            -it \
            --rm \
            --name=protonwire_dev \
            --init \
            -e DEBUG \
            -e PROTONVPN_SERVER \
            -e IPCHECK_INTERVAL=${IPCHECK_INTERVAL:-10} \
            -e KILL_SWITCH=${KILL_SWITCH:-1} \
            -e SKIP_DNS_CONFIG \
            -e IPCHECK_URL \
            --cap-add=CAP_NET_ADMIN \
            --userns=host \
            -p=8000:80 \
            -v $(pwd)/protonwire:/usr/bin/protonwire:ro \
            --mount type=bind,src="$(pwd)"/private.key,dst=/etc/protonwire/private-key,readonly \
            --sysctl net.ipv4.conf.all.rp_filter=2 \
            --tmpfs /tmp \
            "${extra_args[@]}" \
            ghcr.io/tprasadtp/protonwire:dev "${cli_args[@]}"
    fi
}

main "$@"
