#!/usr/bin/env bash
info() {
    local msg="$*"
    printf "==> %s \n" "$msg"
}

info "Pinning workflow/build.yml"
docker run \
    --rm \
    -v $(pwd)/.github/workflows:/workflows:rw \
    --userns=host \
    ghcr.io/sethvargo/ratchet:0.3.0 \
    pin /workflows/build.yml

info "Pinning workflow/metadata.yml"
docker run \
    --rm \
    -v $(pwd)/.github/workflows:/workflows:rw \
    --userns=host \
    ghcr.io/sethvargo/ratchet:0.3.0 \
    pin /workflows/metadata.yml

info "Pinning workflow/release.yml"
docker run \
    --rm \
    -v $(pwd)/.github/workflows:/workflows:rw \
    --userns=host \
    ghcr.io/sethvargo/ratchet:0.3.0 \
    pin /workflows/release.yml
