name: docs
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Update README
        run: make update-readme

      - name: Check if README is up-to date
        run: git diff --exit-code README.md
