name: metadata
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  schedule:
    - cron: "30 * * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Bot Token
        id: bot
        uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06 # ratchet:tibdex/github-app-token@v1.7.0
        with:
          repository: tprasadtp/protonwire-api-deploy
          app_id: 241646
          installation_id: ${{ secrets.APP_INSTALLATION_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout Metadata Repo
        uses: actions/checkout@v3 # ratchet:exclude
        with:
          repository: tprasadtp/protonwire-api-deploy
          path: protonwire-api-deploy
          token: ${{ steps.bot.outputs.token }}
          persist-credentials: true
      - name: Checkout Project Repo
        uses: actions/checkout@v3 # ratchet:exclude
        with:
          persist-credentials: false
      - name: Install
        run: |
          sudo apt-get install -y \
          python3-gnupg \
          python3-requests \
          python3-bcrypt \
          python3-coloredlogs \
          tree
      - name: Sync metadata
        run: tree metadata/
      - name: Generate metadata
        run: ./protonwire/scripts/generate-server-metadata --output ./metadata
        env:
          PROTON_USERNAME: ${{ secrets.PROTON_USERNAME }}
          PROTON_PASSWORD: ${{ secrets.PROTON_PASSWORD }}
      - name: Sync metadata
        run: |
          rsync \
            --archive \
            --human-readable \
            --verbose \
            ./metadata/ \
            ${GITHUB_WORKSPACE}/protonwire-api-deploy/
          tree ${GITHUB_WORKSPACE}/protonwire-api-deploy/
      - name: Push Metadata
        working-directory: protonwire-api-deploy
        run: |
          git config user.name protonwire-api-deploy[bot]
          git config user.email 114404808+protonwire-api-deploy[bot]@users.noreply.github.com
          git add --all
          git commit -m "Updated at - $(date)"
          git push -u origin master
