name: metadata
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  schedule:
    # '*'' is a special character in YAML so
    # you have to quote this string
    - cron: "0 */6 * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        id: metadata
        uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06 # ratchet:tibdex/github-app-token@v1
        with:
          repository: ${{ secrets.METADATA_REPO }}
          app_id: ${{ secrets.APP_ID }}
          installation_id: ${{ secrets.APP_INSTALLATION_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout Metadata Repo
        uses: actions/checkout@v3 # ratchet:exclude
        with:
          repository: ${{ secrets.METADATA_REPO }}
          path: protonvpn-metadata
          token: ${{ steps.metadata.outputs.token }}
          persist-credentials: true
      - name: Checkout Project Repo
        uses: actions/checkout@v3 # ratchet:exclude
        with:
          path: protonwire
          persist-credentials: false
      - name: Install
        run: |
          sudo apt-get install -y \
          python3-gnupg \
          python3-requests \
          python3-bcrypt \
          python3-coloredlogs
      - name: Cleanup stale data
        run: |
          rm -rf ./protonvpn-metadata/v1
      - name: Generate metadata
        run: |
          ./protonwire/scripts/generate-server-metadata \
          --output ./protonvpn-metadata
        env:
          PROTON_USERNAME: ${{ secrets.PROTON_USERNAME }}
          PROTON_PASSWORD: ${{ secrets.PROTON_PASSWORD }}
      - name: Push Metadata
        working-directory: protonvpn-metadata
        run: |
          git config user.name ${{ secrets.GIT_USER_NAME }}
          git config user.email ${{ secrets.GIT_USER_EMAIL }}
          git add --all
          git commit --allow-empty -m "Updated at - $(date)"
          git push -u origin master
