name: "stale"
on:
  schedule:
    - cron: "15 08 * * SAT"
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Debug/Dry Run"
        required: true
        default: "false"
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Check if dry run is set
        id: check_debug
        run: |
          if [[ ${GH_EVENT_NAME} == "workflow_dispatch" ]]; then
            if [[ ${GH_INPUT_DRY_RUN} != "false" ]]; then
              echo "::set-output name=result::true"
            else
              echo "::set-output name=result::false"
            fi
          else
            echo "::set-output name=result::false"
          fi
        env:
          GH_EVENT_NAME: ${{ github.event_name }}
          GH_INPUT_DRY_RUN: ${{ github.event.inputs.dry_run }}

      - uses: actions/stale@v4
        with:
          # Dry run
          debug-only: ${{ steps.check_debug.outputs.result }}
          enable-statistics: true
          # Issues
          stale-issue-message: "This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 14 days."
          close-issue-message: "This issue was closed because it has been stalled for 14 days with no activity."
          stale-issue-label: "Status:Stale"
          days-before-issue-stale: 60
          days-before-issue-close: 14

          # PRs
          days-before-pr-stale: 60
          days-before-pr-close: 30
          stale-pr-label: "Status:Stale"
          close-pr-message: "This PR was closed because it has been stalled for 30 days with no activity."
          stale-pr-message: "This PR is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 30 days."

          # Milestones
          exempt-all-pr-milestones: true

          # do not act on following Labels
          exempt-issue-labels: "Actor:Luna,Status:Keep-Open,Status:Pending,Status:Blocked,Priority:Critical"
          exempt-pr-labels: "Actor:Luna,Status:Keep-Open,Status:Pending,Status:Blocked,Priority:Critical"
